version: 2

project_name: terradozer

builds:
  - id: terradozer
    binary: terradozer
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/chenrui333/terradozer/internal.version={{.Version}} -X github.com/chenrui333/terradozer/internal.commit={{.ShortCommit}} -X github.com/chenrui333/terradozer/internal.date={{.Date}}

archives:
  - id: terradozer
    formats:
      - tar.gz
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
