// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/resource/destroy.go
//
// Generated by this command:
//
//	mockgen -source=pkg/resource/destroy.go -destination=pkg/resource/destroy_mock_test.go -package=resource_test
//

// Package resource_test is a generated GoMock package.
package resource_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDestroyableResource is a mock of DestroyableResource interface.
type MockDestroyableResource struct {
	ctrl     *gomock.Controller
	recorder *MockDestroyableResourceMockRecorder
	isgomock struct{}
}

// MockDestroyableResourceMockRecorder is the mock recorder for MockDestroyableResource.
type MockDestroyableResourceMockRecorder struct {
	mock *MockDestroyableResource
}

// NewMockDestroyableResource creates a new mock instance.
func NewMockDestroyableResource(ctrl *gomock.Controller) *MockDestroyableResource {
	mock := &MockDestroyableResource{ctrl: ctrl}
	mock.recorder = &MockDestroyableResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestroyableResource) EXPECT() *MockDestroyableResourceMockRecorder {
	return m.recorder
}

// Destroy mocks base method.
func (m *MockDestroyableResource) Destroy() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy")
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockDestroyableResourceMockRecorder) Destroy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockDestroyableResource)(nil).Destroy))
}

// ID mocks base method.
func (m *MockDestroyableResource) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDestroyableResourceMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDestroyableResource)(nil).ID))
}

// Type mocks base method.
func (m *MockDestroyableResource) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockDestroyableResourceMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockDestroyableResource)(nil).Type))
}
